Make the jump commands wrap around
mgedmin/coverage-highlight.vim pull request #27
Opened 2021-11-06 02:13 UTC by jwodder

This PR modifies the `:NextUncovered` command so that, when it is invoked when the cursor is after the last uncovered block, the cursor moves to the first uncovered block, and similarly for `:PrevUncovered`.  The PR also fixes a typo in the message previously shown when there are no uncovered lines below/above the current line (now only shown when there are no uncovered lines in the whole file).

2021-11-06 12:30 UTC, mgedmin requested changes
I don't want to do this unconditionally.  How about checking the &wrapscan option?

I'd prefer if the `find_next_range/find_prev_range` helpers didn't wrap around, then we could have jump_to_next/jump_to_prev check &wrapscan and either jump to the 1st or the last range, or print an appropriate error message ('No highlighted lines in buffer' when wrapscan is enabled, 'No highlighted lines below/above' when it's disabled).

2021-11-06 12:30 UTC, mgedmin commented on pythonx/coverage_highlight.py
> +        print("No highlighted lines below cursor")
Augh!  That word is my nemesisisssis.

2021-11-06 12:46 UTC, mgedmin commented on pythonx/coverage_highlight.py
> +        print("No highlighted lines below cursor")
(Fixed in master)

2021-11-06 18:37 UTC, jwodder commented
@mgedmin I've updated the PR so that wraparound is only in effect if the `&wrapscan` option is set.

2021-11-07 21:28 UTC, mgedmin approved these changes
LGTM!

2021-11-07 21:28 UTC, mgedmin commented on pythonx/coverage_highlight.py
> +                next_range = None
Oooh thank you for considering this corner case!  I would've forgotten to check for it while reviewing.

2021-11-07 21:29 UTC, merged